#!/bin/sh

set -x

echo "Change to node-app dir"
cd ~/node-app
echo "Git pull"
    git pull origin master
echo "install node"
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0

echo "npm install"
    npm install
echo "install pm2"
    npm install -g nodemon pm2
echo "restart"
    pm2 restart ecosystem.config.js
    exit
