#!/bin/sh

set -x

echo "SUI: Change to node-app diri to start"
#cd /home/ubuntu/node-app
echo $(pwd)
echo "SUI: Git pull"
    git pull origin master
echo "SUI: install node"
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0

echo "SUI: npm install"
    npm install
echo "SUI: install pm2"
    npm install -g nodemon pm2
echo "SUI: restart"
    pm2 restart ecosystem.config.js
    exit
